name: linter

permissions:
  pull-requests: write
  contents: read

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version to use'
        required: false
        default: '1.22'
        type: string

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{inputs.go-version}}

      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--timeout=5m"
          reporter: github-pr-review
          fail_level: error
          golangci_lint_version: latest